sonar.projectKey=codeartstest_july24
sonar.organization=codeartstest
sonar.sources=backend,frontend/src
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/coverage/**
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
