sonar.projectKey=codeartstest
sonar.organization=codeartstest
sonar.sources=backend,frontend/src
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/coverage/**
